# Generated by Django 3.0.7 on 2020-06-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputadometrics',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
