# Generated by Django 3.0.7 on 2020-06-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_deputadometrics_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deputadometrics',
            name='id',
        ),
        migrations.AlterField(
            model_name='deputadometrics',
            name='external_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
