# Generated by Django 3.0.7 on 2020-06-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_auto_20200610_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputadometrics',
            name='external_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
