# Generated by Django 3.0.10 on 2020-10-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_auto_20200610_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deputadometrics',
            name='twitter',
        ),
    ]
