version: '3.7'

services:
  db:
    image: postgres:12-alpine
    env_file:
      - ./.env
    restart: always
    volumes:
      - acompanha_data:/var/lib/postgresql/data

  api:
    image: acompanha_legis_api
    env_file:
      - ./.env
    volumes:
      - nginx:/etc/nginx/conf.d
      - acompanha_static:/var/acompanha_legis/api/static
    depends_on:
      - db

  tasks:
    image: acompanha_legis_tasks
    depends_on:
      - db
    command: -d "Nome Deputado" -o /var/acompanha_legis

  portal:
    image: acompanha_legis_portal

  nginx:
    image: nginx:alpine
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - nginx:/etc/nginx/conf.d
      - acompanha_static:/var/acompanha_legis/api/static
    depends_on:
      - api
      - portal
    ports:
      - 80:80

volumes:
  acompanha_data:
  acompanha_static:
  nginx:
