version: '3.7'

services:
  db:
    image: postgres:12
    env_file:
      - ./.env
    restart: always
    volumes:
      - acompanha_data:/var/lib/postgresql/data
  api:
    build: .
    command: python ./api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/acompanha-legis:cached
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  acompanha_data:
