version: '3.7'

services:
  db:
    image: postgres:12-alpine
    env_file:
      - ./.env
    restart: always
    volumes:
      - acompanha_data:/var/lib/postgresql/data

  api:
    build: api/.
    env_file:
      - ./.env
    volumes:
      - ./api:/opt/acompanha_legis:cached
      - nginx:/etc/nginx/conf.d
      - acompanha_static:/var/acompanha_legis/api/static
    depends_on:
      - db
    command: python ./api/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  smtp:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025

  tasks:
    build: acompanha_legis/.
    depends_on:
      - db

  portal:
    image: acompanha_legis_portal

  nginx:
    image: nginx:alpine
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - nginx:/etc/nginx/conf.d
      - acompanha_static:/var/acompanha_legis/api/static
    depends_on:
      - api
    ports:
      - 80:80

volumes:
  acompanha_data:
  acompanha_static:
  nginx:
