# Generated by Django 3.0.10 on 2020-10-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_auto_20200610_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritedeputado',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='favoritedeputado',
            name='partido',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='favoriteproposicao',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
